---
postgresql_global_config_options:
  - option: unix_socket_directories
    value: '{{ postgresql_unix_socket_directories | join(",") }}'
  - option: log_directory
    value: 'log'
  - option: listen_addresses
    value: '*'

postgresql_hba_entries:
  - {type: local, database: all, user: postgres, auth_method: peer}
  - {type: local, database: all, user: all, auth_method: peer}
  - {type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: "{{ postgresql_auth_method }}"}
  - {type: host, database: all, user: all, address: '::1/128', auth_method: "{{ postgresql_auth_method }}"}
  - {type: host, database: nextcloud, user: flexbiz, address: '172.16.0.0/12', auth_method: "{{ postgresql_auth_method }}"}
  - {type: host, database: colibri_stat_db, user: "{{ colibri_stat_db_user }}", address: '172.18.0.0/12', auth_method: "{{ postgresql_auth_method }}"}

postgresql_users:
  - name: flexbiz
    password: "{{ flexbiz_password }}"
  - name: "{{ colibri_stat_db_user }}"
    password: "{{ colibri_stat_db_password }}"

postgresql_databases:
  - name: nextcloud
    owner: flexbiz
  - name: colibri_stat_db
    owner: "{{ colibri_stat_db_user }}"