pgbackrest_version: 2.58.0
pgbackrest_user: postgres
pgbackrest_group: postgres
pgbackrest_configuration_global_options:
  start-fast: y
pgbackrest_configuration_stanzas:
- name: flexbiz
  hosts:
    - options:
        path: '/var/lib/postgresql/15/main'
pgbackrest_configuration_repositories:
  - options:
      path: /var/lib/pgbackrest
      retention-full: 1
      block: y
      bundle: y
      cipher-pass: "{{ pgbackrest_cipher_pass }}"
      cipher-type: aes-256-cbc
  - options:
      path: /pgbackrest/{{ inventory_hostname }}
      retention-full: 4
      s3-bucket: "{{ s3_bucket }}"
      s3-endpoint: "{{ s3_endpoint }}"
      s3-key: "{{ s3_key }}"
      s3-key-secret: "{{ s3_secret }}"
      s3-region: eu-central-003
      type: s3
      cipher-pass: "{{ pgbackrest_cipher_pass }}"
      cipher-type: aes-256-cbc
pgbackrest_configuration_archive_push_options:
  compress-level: 3
pgbackrest_backup_cron:
    - stanza: flexbiz
      type: full
      weekday: SUN
      hour: 4
      minute: 30
      name: Full backup
    - stanza: flexbiz
      type: incr
      day: '*'
      hour: '09,12,16,23'
      minute: 0
      name: Incremental backup