pgbackrest_conf_cluster_stanzas:
  flexbiz:
    pg1-path: '/var/lib/postgresql/15/main'
  global:
    repo1-path: /var/lib/pgbackrest
    repo1-retention-full: 4
    repo1-block: y
    repo1-bundle: y
    repo1-cipher-pass: "{{ pgbackrest_cipher_pass }}"
    repo1-cipher-type: aes-256-cbc
    start-fast: y
pgbackrest_systemd_timer_enabled: true
pgbackrest_cron_enabled: false
pgbackrest_full_backup_systemd_timer_oncalendar: "Sun *-*-* 04:30:00"
pgbackrest_incr_backup_systemd_timer_oncalendar: "Mon..Sat *-*-* 09,12,16,23:00:00"
pgbackrest_diff_backup_systemd_timer_oncalendar: null
pgbackrest_postgresql_conf_path: '/etc/postgresql/15/main/postgresql.conf'
pgbackrest_postgresql_conf:
  archive_command: "pgbackrest --config={{ pgbackrest_conf_path }} --stanza=flexbiz archive-push %p"
  archive_mode: "on"
  log_filename: "postgresql.log"
  max_wal_senders: 3
  wal_level: replica

# This is a convenience script included in this role for restoring from
# backups. You can set this to null to avoid having it installed.
pgbackrest_restore_script_path: /usr/local/bin/pgbackrest_restore

# This is a convenience script included in this role for making backups
# with pgbackrest. It mainly simplifies passing multiple stanzas for backup,
# and is used by the scheduled systemd or cron jobs, so disabling the
# installation of this file by setting `pgbackrest_backup_script_path` to
# null should only happen when you're also not using the timer/cron jobs
# that come with this role.
pgbackrest_backup_script_path: /usr/local/bin/pgbackrest_backup