---
restic_repos:
  remote:
    location: rclone:DigiStorage:/restic/{{ inventory_hostname }}
    password: "{{ restic_repo_pass }}"
    init: true

restic_backups:
  data:
    name: data
    repo: remote
    src: /data
    keep_within: 1y
    scheduled: true
    schedule_hour: 3
    schedule_minute: 0