---
restic_repos:
  remote:
    location: s3:{{ s3_endpoint }}/{{ s3_bucket }}
    password: "{{ restic_repo_pass }}"
    init: true
    aws_access_key: "{{ s3_key }}"
    aws_secret_access_key: "{{ s3_secret }}"

restic_backups:
  data:
    name: data
    repo: remote
    src: /data
    keep_within: 1y
    scheduled: true
    schedule_hour: 3
    schedule_minute: 0