---
- name: Place remote backup script
  template:
    src: remote-backup.sh.j2
    dest: /usr/local/bin/remote-backup.sh
    mode: '0700'

- name: Add rclone full backup cron
  ansible.builtin.cron:
    name: "rclone full backup"
    weekday: "SUN"
    minute: "5"
    hour: "5"
    job: "/usr/local/bin/remote-backup.sh >> /var/log/cron.log 2>&1"
  when: setup_rclone_config.changed

- name: Add rclone incr backup cron
  ansible.builtin.cron:
    name: "rclone incr backup"
    weekday: "MON-SAT"
    minute: "15"
    hour: "9,12,16,23"
    job: "/usr/local/bin/remote-backup.sh >> /var/log/cron.log 2>&1"
  when: setup_rclone_config.changed