services:
  fider:
    image: 'getfider/fider:stable'
    environment:
      - SERVICE_URL_FIDER_3000
      - BASE_URL=$SERVICE_URL_FIDER
      - 'DATABASE_URL=postgres://$SERVICE_USER_POSTGRES:$SERVICE_PASSWORD_POSTGRES@database:5432/fider?sslmode=disable'
      - JWT_SECRET=$SERVICE_PASSWORD_64_FIDER
      - 'EMAIL_NOREPLY={{environment.SMTP_USERNAME}}'
      - EMAIL_MAILGUN_API=$EMAIL_MAILGUN_API
      - EMAIL_MAILGUN_DOMAIN=$EMAIL_MAILGUN_DOMAIN
      - EMAIL_MAILGUN_REGION=$EMAIL_MAILGUN_REGION
      - 'EMAIL_SMTP_HOST={{environment.SMTP_HOST}}'
      - 'EMAIL_SMTP_PORT={{environment.SMTP_PORT}}'
      - 'EMAIL_SMTP_USERNAME={{environment.SMTP_USERNAME}}'
      - 'EMAIL_SMTP_PASSWORD={{environment.SMTP_PASSWORD}}'
      - EMAIL_SMTP_ENABLE_STARTTLS=true
      - EMAIL_AWSSES_REGION=$EMAIL_AWSSES_REGION
      - EMAIL_AWSSES_ACCESS_KEY_ID=$EMAIL_AWSSES_ACCESS_KEY_ID
      - EMAIL_AWSSES_SECRET_ACCESS_KEY=$EMAIL_AWSSES_SECRET_ACCESS_KEY
    healthcheck:
      test:
        - CMD
        - /app/fider
        - ping
      interval: 2s
      timeout: 10s
      retries: 10
  database:
    image: 'postgres:12'
    volumes:
      - 'pg_data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=$SERVICE_USER_POSTGRES
      - POSTGRES_PASSWORD=$SERVICE_PASSWORD_POSTGRES
      - 'POSTGRES_DB=${POSTGRES_DB:-fider}'
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}'
      interval: 5s
      timeout: 20s
      retries: 10
