services:
  fmd:
    image: 'registry.gitlab.com/fmd-foss/fmd-server:0.14.2'
    container_name: fmd
    environment:
      - SERVICE_FQDN_FMD_8080
    volumes:
      - '/data/fmddata/:/var/lib/fmd-server/db/'
    restart: unless-stopped
