services:
  migrations:
    image: 'mediacms/mediacms:7'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - '/data/mediacms/:/home/mediacms.io/mediacms/'
      - '/videos/:/home/mediacms.io/videos/'
    environment:
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_CELERY_BEAT: 'no'
      ADMIN_USER: '${ADMIN_USER}'
      ADMIN_EMAIL: '${ADMIN_EMAIL}'
    command: ./deploy/docker/prestart.sh
    restart: on-failure
    depends_on:
      redis:
        condition: service_healthy
  web:
    image: 'mediacms/mediacms:7'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    deploy:
      replicas: 1
    volumes:
      - '/data/mediacms/:/home/mediacms.io/mediacms/'
      - '/videos/:/home/mediacms.io/videos/'
    environment:
      SERVICE_FQDN_MEDIA_80: null
      ENABLE_CELERY_BEAT: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_MIGRATIONS: 'no'
    depends_on:
      - migrations
  celery_beat:
    image: 'mediacms/mediacms:7'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - '/data/mediacms/:/home/mediacms.io/mediacms/'
      - '/videos/:/home/mediacms.io/videos/'
    environment:
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_MIGRATIONS: 'no'
    depends_on:
      - redis
  celery_worker:
    image: 'mediacms/mediacms:7'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    deploy:
      replicas: 1
    volumes:
      - '/data/mediacms/:/home/mediacms.io/mediacms/'
      - '/videos/:/home/mediacms.io/videos/'
    environment:
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_BEAT: 'no'
      ENABLE_MIGRATIONS: 'no'
    depends_on:
      - migrations
  redis:
    image: 'redis:alpine'
    restart: always
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 10s
      timeout: 5s
      retries: 3
