services:
  nextcloud:
    image: 'lscr.io/linuxserver/nextcloud:32.0.1'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - PUID=200
      - PGID=200
      - 'TZ=${TZ:-Europe/Bucharest}'
      - 'POSTGRES_DB=${POSTGRES_DB:-nextcloud}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - POSTGRES_HOST=host.docker.internal
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - 'NEXTCLOUD_ADMIN_PASSWORD=${ADMIN_PASSWORD}'
      - 'NEXTCLOUD_ADMIN_USER=${ADMIN_USER}'
    volumes:
      - '/data/nextcloud:/config'
      - '/mnt/nextcloud:/data'
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1:80'
      interval: 2s
      timeout: 10s
      retries: 15
  redis:
    image: 'redis:7.4-alpine'
    volumes:
      - 'nextcloud-redis-data:/data'
    healthcheck:
      test:
        - CMD
        - redis-cli
        - PING
      interval: 5s
      timeout: 10s
      retries: 20
  collabora:
    image: collabora/code:25.04.6.2.1
    container_name: collabora
    restart: always
    environment:
      - 'extra_params=--o:server_name=docs.flexbiz.ro --o:ssl.enable=false --o:ssl.termination=true --o:user_interface.use_integration_theme=false'
      - domain=cloud.flexbiz.ro
