services:
  web:
    image: 'xwiki:17.10-postgres-tomcat'
    container_name: xwiki-postgres-tomcat-web
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - SERVICE_FQDN_WIKI_8080
      - XWIKI_VERSION=17.10
      - 'DB_USER=${SERVICE_USER_POSTGRESQL}'
      - 'DB_PASSWORD=${SERVICE_PASSWORD_POSTGRESQL}'
      - 'DB_DATABASE=${DATABASE_POSTGRESQL}'
      - DB_HOST=host.docker.internal
    volumes:
      - '/data/xwiki:/usr/local/xwiki'
      - '/data/xwiki/xwiki.properties:/usr/local/tomcat/webapps/ROOT/WEB-INF/xwiki.properties'
      - '/mnt/xwiki:/data/store/file'
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1:8080'
      interval: 2s
      timeout: 10s
      retries: 15
