services:
  postgres:
    image: 'postgres:16-alpine'
    environment:
      - 'POSTGRES_USER=${SERVICE_USER_POSTGRESQL}'
      - 'POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRESQL}'
      - 'POSTGRES_DB=${POSTGRESQL_DATABASE:-glitchtip}'
    restart: unless-stopped
    volumes:
      - 'glitchtip-postgres-data:/var/lib/postgresql/data'
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'
      interval: 5s
      timeout: 20s
      retries: 10
  valkey:
    image: 'valkey/valkey:9'
    restart: unless-stopped
  web:
    image: 'glitchtip/glitchtip:6'
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SERVER_ROLE=all_in_one
      - 'DATABASE_URL=postgres://$SERVICE_USER_POSTGRESQL:$SERVICE_PASSWORD_POSTGRESQL@postgres:5432/${POSTGRESQL_DATABASE:-glitchtip}'
      - 'VALKEY_URL=redis://valkey:6379'
      - SECRET_KEY=$SERVICE_BASE64_64_ENCRYPTION
      - 'EMAIL_URL=${EMAIL_URL:-consolemail://}'
      - 'GLITCHTIP_DOMAIN=https://glitchtip.flexbiz.ro'
      - 'DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL:-test@example.com}'
      - ENABLE_USER_REGISTRATION=false
      - ENABLE_ADMIN=True
      - ENABLE_OPENAPI=True
      - GLITCHTIP_ENABLE_MCP=False
      - GLITCHTIP_ENABLE_DUCKDB=False
    restart: unless-stopped
    volumes:
      - 'uploads:/code/uploads'
    healthcheck:
      test:
        - CMD
        - echo
        - ok
      interval: 5s
      timeout: 20s
      retries: 10
