services:
  grafana:
    image: grafana/grafana
    user: '0'
    environment:
      - SERVICE_URL_GRAFANA_3000
      - 'GF_SERVER_ROOT_URL=${SERVICE_URL_GRAFANA}'
      - 'GF_SERVER_DOMAIN=${SERVICE_URL_GRAFANA}'
      - 'GF_SECURITY_ADMIN_PASSWORD=${SERVICE_PASSWORD_GRAFANA}'
      - 'GF_SECURITY_ADMIN_USER=${SERVICE_USER_GRAFANA}'
    volumes:
      - '/data/grafana:/var/lib/grafana'
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1:3000/api/health'
      interval: 5s
      timeout: 20s
      retries: 10
  prometheus:
    image: prom/prometheus
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - '/data/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro'
      - '/data/prometheus/rules:/etc/prometheus/rules:ro'
      - 'prometheus-data:/prometheus'
  alertmanager:
    image: 'prom/alertmanager:v0.31.1'
    restart: unless-stopped
    volumes:
      - '/data/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml'
      - 'alertmanager-data:/alertmanager'
  node_exporter:
    image: 'quay.io/prometheus/node-exporter:v1.10.2'
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      DATA_SOURCE_URI: '${POSTGRES_URL}'
      DATA_SOURCE_USER: '${POSTGRES_USER}'
      DATA_SOURCE_PASS: '${POSTGRES_PASS}'
    restart: unless-stopped
  restic-exporter:
    image: ngosang/restic-exporter
    environment:
      - TZ=Europe/Bucharest
      - 'RESTIC_REPOSITORY=${RESTIC_REPO_URL}'
      - 'RESTIC_PASSWORD=${restic_repo_pass}'
      - 'AWS_ACCESS_KEY_ID=${s3_key}'
      - 'AWS_SECRET_ACCESS_KEY=${s3_secret}'
      - REFRESH_INTERVAL=86400
    volumes:
      - '/root/.cache/restic:/root/.cache/restic'
    restart: unless-stopped
  logporter:
    image: 'lifailon/logporter:latest'
    restart: unless-stopped
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    environment:
      - DOCKER_LOG_METRICS=false
      - DOCKER_LOG_CUSTOM_METRICS=false
      - 'DOCKER_LOG_CUSTOM_QUERY=\"(err|error|ERR|ERROR)\"'
  pgbackrest-exporter:
    image: 'ghcr.io/woblerr/pgbackrest_exporter:v0.23.0'
    restart: unless-stopped
    environment:
      - BACKREST_USER=postgres
      - BACKREST_UID=102
      - BACKREST_GROUP=postgres
      - BACKREST_GID=110
      - TZ=Europe/Bucharest
      - COLLECT_INTERVAL=86400
    volumes:
      - '/etc/pgbackrest/pgbackrest.conf:/etc/pgbackrest/pgbackrest.conf:ro'
      - '/var/lib/pgbackrest:/var/lib/pgbackrest:ro'
