services:
  wg-easy:
    image: 'ghcr.io/wg-easy/wg-easy:latest'
    restart: unless-stopped
    environment:
      - PASSWORD_HASH
      - 'WG_HOST=https://vpn.flexbiz.ro'
      - 'LANG=${LANG:-en}'
      - PORT=8000
      - WG_PORT=51820
      - WG_ALLOWED_IPS=10.8.0.0/24
    volumes:
      - 'wg-easy:/etc/wireguard'
    ports:
      - '51820:51820/udp'
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1