---

- name: Ensure letsencrypt directory exists
  ansible.builtin.file:
    path: /mnt/letsencrypt
    state: directory

- name: Ensure portainer directory exists
  ansible.builtin.file:
    path: /mnt/portainer
    state: directory

- name: Ensure mnt has read permissions for filestash
  ansible.builtin.file:
    path: /mnt
    state: directory
    recurse: yes
    mode: '0755'

- name: Ensure filestash directory exists
  ansible.builtin.file:
    path: /mnt/filestash
    state: directory
    mode: '0777'

- name: Place base_stack.yml file
  template:
    src: base_stack.yml.j2
    dest: /opt/base_stack.yml

- name: Deploy base_stack.yml
  community.docker.docker_stack:
    state: present
    name: base_stack
    compose:
      - /opt/base_stack.yml