---

- name: Ensure mysql directory exists
  ansible.builtin.file:
    path: /mnt/mysql
    state: directory
    mode: '0765' #needed for filestash

- name: Ensure wordpress directory exists
  ansible.builtin.file:
    path: /mnt/wordpress
    state: directory
    mode: '0765' #needed for filestash

- name: Place cms_stack.yml file
  template:
    src: cms_stack.yml.j2
    dest: /opt/cms_stack.yml

- name: Deploy cms_stack.yml
  community.docker.docker_stack:
    state: present
    name: cms_stack
    compose:
      - /opt/cms_stack.yml