---

- name: Install requirements
  package:
    name: 
      - python3-jsondiff
    state: present

- name: configure initial swarm stack
  become: true
  block:
    - name: place initial_stack.yml file
      template:
        src: initial_stack.yml.j2
        dest: /opt/initial_stack.yml

    - name: Create web network
      docker_network:
        name: web
        driver: "overlay"

    - name: Deploy stack from the compose file
      community.docker.docker_stack:
        state: present
        name: initial_stack
        compose:
          - /opt/initial_stack.yml

    - name: check port 80 is opened
      wait_for:
        port: "80"
        timeout: 30

    - name: check port 443 is opened
      wait_for:
        port: "443"
        timeout: 30