services:
  nexus:
    image: sonatype/nexus3
    platform: linux/amd64
    environment:
      - SERVICE_FQDN_NEXUS_8081
      - 'NEXUS_SECURITY_RANDOMPASSWORD=${NEXUS_SECURITY_RANDOMPASSWORD:-false}'
      - 'INSTALL4J_ADD_VM_PARAMS=-Xms2703m -Xmx2703m -XX:MaxDirectMemorySize=2703m -Djava.util.prefs.userRoot=/nexus-data/javaprefs'
    volumes:
      - '/mnt/nexus_data:/nexus-data'
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:8081/service/rest/v1/status'
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 60s
