---

- hosts: database
  become: yes
  roles:
    - geerlingguy.postgresql
    - dudefellah.pgbackrest
    - stefangweichinger.ansible_rclone
    - database
    - role: netdata
      when: claim_token is defined

- hosts: manager
  become: yes
  roles:
    - role: netdata
      when: claim_token is defined
    - ansible-role-seaweedfs
    - atosatto.docker-swarm

- hosts: data
  become: yes
  roles:
    - role: netdata
      when: claim_token is defined
    - ansible-role-seaweedfs
    - stefangweichinger.ansible_rclone
    - andrewrothstein.restic
    - restic-init