---

- hosts: main-server
  become: yes
  roles:
    - geerlingguy.postgresql
    - dudefellah.pgbackrest
    - data
    - role: andrewrothstein.restic
      when: restic_repo_pass is defined
    - role: restic-init
      when: restic_repo_pass is defined
    - role: netdata
      when: claim_token is defined
    - sentry