---

- hosts: main_server
  become: yes
  roles:
    - geerlingguy.postgresql
    - dudefellah.pgbackrest
    - stefangweichinger.ansible_rclone
    - database
    - role: andrewrothstein.restic
      when: restic_repo_pass is defined
    - role: restic-init
      when: restic_repo_pass is defined
    - role: netdata
      when: claim_token is defined