---

- hosts: database
  become: yes
  roles:
    - geerlingguy.postgresql
    - dudefellah.pgbackrest
    - stefangweichinger.ansible_rclone
    - database
    - role: netdata
      when: claim_token is defined

- hosts: weed_master
  become: yes
  roles:
    - role: netdata
      when: claim_token is defined
    - ansible-role-seaweedfs

- hosts: weed_volume
  become: yes
  roles:
    - role: netdata
      when: claim_token is defined
    - ansible-role-seaweedfs

- hosts: weed_filer
  become: yes
  roles:
    - role: netdata
      when: claim_token is defined
    - ansible-role-seaweedfs