---
restic_install_path: '/usr/local/bin'

restic_script_dir: '/root/restic'
restic_log_dir: '{{ restic_script_dir }}/log'
restic_repos: {}
restic_backups: []
restic_create_cron: true

restic_dir_owner: '{{ ansible_user | default(ansible_user_id) }}'
restic_dir_group: '{{ ansible_user | default(ansible_user_id) }}'

restic_backup_script_template: restic_script_Linux.j2